### ISSUE TITLE
Starttime in adv_analysis

### ISSUE THREAD

**Issue by dmkahler** [hydro-lab/turbulent-mixing#1]
We need a starttime variable at line 32 to pass to the plotting features.  Use date and time data from variable: sen.  These functions may be useful:
[Lubridate](https://lubridate.tidyverse.org/) - a library that allows storage as number of seconds since 01 Jan 1970
[as.Date](https://www.statmethods.net/input/dates.html) - built-in function that can put pieces into date format
[paste](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/paste) - to create inputs

With this, we should be able to remove dat$time on line 79 and use time[i] (defined on line 98) for plotting.

**Comment by bachtlina** [comment]
The starttime variable is now correct. The next step is to fix the time assigned to each averaged window.

**Comment by dmkahler** [comment]
Added depth analysis; but we didn't measure to 25 m.  Check the math on the depth calculation.

**Comment by dmkahler** [comment]
check the conversion also.

**Comment by dmkahler** [comment]
added start and end time search.  PLEASE CHECK.

**Comment by dmkahler** [comment]
Starttime fixed.  Also added code to find times in data.  Next, use start and end time to evaluate each depth, which will move to a new issue.
